site_name: Comet
site_url: https://angrybino.github.io/Comet
site_description: 'Comet is an advanced framework designed to properly abstract server-client communication in the right way and provide other useful utilities for better game development workflow.'
site_author: 'angrybino'
copyright: Copyright &copy; 2021 - 2022 angrybino

docs_dir: docs/
repo_name: 'Comet'
repo_url: 'https://github.com/angrybino/Comet'
edit_uri: edit/master/docs

theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.integrate
  favicon: Assets/Images/Logo.png
  logo: Assets/Images/Logo.png
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    scheme: default
    primary: white
    accent: light blue
extra_css:
  - Stylesheets/Custom.css
 
nav:
  - Home: index.md
  - Getting started:
    - Setting up: Gettingstarted/Settingup.md
    - Basic usage: Gettingstarted/Basicusage.md

  - Services: Services.md
  - Controllers : Controllers.md
  - Lifecycle: Lifecycle.md
  - Utilities:
    - Remote: 
      - RemoteSignal: Util/Remote/RemoteSignal.md
  - API: API.md

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
        guess_lang: false
  - toc:
        permalink: true
  - def_list
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
        smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
        custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.highlight
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
     custom_checkbox: true