site_name: Comet
site_url: https://angrybino.github.io/Comet
site_description: Comet is an advanced framework designed to properly abstract server-client communication in the right way and provide other useful utilities for better game development workflow.
site_author: angrybino
copyright: Copyright &copy; 2021 - 2022 angrybino

docs_dir: docs/
repo_name: Comet
repo_url: https://github.com/angrybino/Comet
edit_uri: edit/master/docs

theme:
  favicon: Assets/Images/Logo.png
  logo: Assets/Images/Logo.png
  name: material
  font:
    text: Ubuntu
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: gray
      accent: light blue
  highlightjs: true
  hljs_languages:
    - lua

nav:
  - Home: index.md
  - Getting started: Gettingstarted.md
  - Services: Services.md
  - Controllers : Controllers.md
  - Lifecycle: Lifecycle.md
  - Util:
    - Shared:
      - Remote: 
        - RemoteSignal: Util/Remote/RemoteSignal.md
      

  - API: API.md
 
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences